import './globals.css';
import '@coinbase/onchainkit/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { type ReactNode } from 'react';
import { GoogleOAuthProvider } from '@react-oauth/google';
import { cookieToInitialState } from 'wagmi';
import { config } from './config';
import { Providers } from './providers';
import { Navbar } from './components/navbar';
import { NavbarN } from './components/navbar-next';
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    config,
    headers().get('cookie')
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
            {/* <Navbar /> */}
            <NavbarN />
            {props.children}
          </GoogleOAuthProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
