import './globals.css';
import '@coinbase/onchainkit/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { type ReactNode } from 'react';
import { GoogleOAuthProvider } from '@react-oauth/google';
import { cookieToInitialState } from 'wagmi';
import { config } from './config';
import { Providers } from './providers';
import { Navbar } from './components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    config,
    headers().get('cookie')
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <GoogleOAuthProvider clientId={"924912220185-pkj4g095ctqmk2ajct469ldbh89bgh43.apps.googleusercontent.com"}>
            <Navbar />
            {props.children}
          </GoogleOAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
